name: Auto Assign Reviewers

on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  assign:
    runs-on: ubuntu-latest

    steps:
      - name: Auto assign reviewers
        uses: wow-actions/auto-assign@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          # Reviewers (puedes agregar m√°s)
          reviewers: |
            jesuviloria
            agutierrezreginodev

          # Habilitar reales reviewers
          addReviewers: true

          # Asignar autom√°ticamente el autor como assignee
          addAssignees: author

          # No limitar cantidad (0 = usar todos los reviewers)
          numberOfReviewers: 0
          numberOfAssignees: 0

          # Skip si el PR es draft
          skipDraft: false   # <-- equivalente correcto
            
      - name: Add note when PR becomes Ready for Review
        if: github.event.action == 'ready_for_review'
        uses: peter-evans/create-or-update-comment@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            üöÄ El pull request ahora est√° listo para revisi√≥n. ¬°Gracias!
