name: Auto Assign Reviewers

on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - name: Assign reviewers
        uses: wow-actions/auto-assign@v2.0.0
        with:
          reviewers: jesuviloria
          skip_review_if_draft: false

      - name: Add note when PR becomes Ready for Review
        if: github.event.action == 'ready_for_review'
        uses: actions-ecosystem/action-add-comment@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          comment: |
            ðŸš€ Thanks! This PR is now ready for review.
