name: Auto Label PRs

on:
  pull_request:

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: Add Documentation label
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: documentation

      - name: Label based on develop branch
        if: github.base_ref == 'develop'
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: docs-feature

      - name: Label based on master branch
        if: github.base_ref == 'master'
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: docs-release
